### ISSUE TITLE
Java Triple Quotes not working properly

### ISSUE THREAD

**Issue by chiqors** [Vulfpeck/jetbrains-fleet-theme#2]
I have this weird bug while coding by using jdk 17, Syntax highlighting colors are not working as intended.

Take a look here
![image](https://user-images.githubusercontent.com/13832788/196990827-1c9f2b5e-6363-4db3-93e7-eca9a6c75243.png)

**Comment by Vulfpeck** [comment]
Hello @chiqors - thanks for raising this issue. Could you please post the code sample as well so I can try it out locally?

**Comment by chiqors** [comment]
> Hello @chiqors - thanks for raising this issue. Could you please post the code sample as well so I can try it out locally?

I only give you the sample project.
this is my repo: https://github.com/chiqors/java17-plain

**Comment by Vulfpeck** [comment]
![image](https://user-images.githubusercontent.com/11810442/197123052-8bafed96-465f-4d91-b0d7-c53956b5da5d.png)

Looks like this issue happens with the default theme as well, so seems like a vscode thing rather than the theme. Closing this issue.

**Comment by chiqors** [comment]
Java extension pack by microsoft and redhat solve the case if you install it. But, you need to disable this theme and use default dark+ theme
